"""Shared constants for VIDA."""

SYSTEM_PROMPT = (
    "You are a professional interior designer. Based on the images and "
    "requirements, identify the user's latent needs and formulate appropriate "
    "questions. Please understand which element should be the primary focus of "
    "your inquiry, then pose only one question at a time. Avoid asking multiple "
    "questions simultaneously. Keep your word count within the limits of a "
    "single question, ensuring it remains concise and not overly complex."
)

CATEGORY_KEYWORDS = {
    "Home Structure": [
        "structure",
        "wall",
        "floor",
        "ceiling",
        "window",
        "door",
        "beam",
        "column",
        "layout",
        "open plan",
        "renovate",
        "demolish",
        "partition",
    ],
    "Spatial Information": [
        "dimension",
        "size",
        "measurement",
        "area",
        "square meter",
        "sqm",
        "width",
        "height",
        "length",
        "scale",
        "plan",
        "blueprint",
    ],
    "Budget": [
        "budget",
        "cost",
        "price",
        "spend",
        "expensive",
        "cheap",
        "range",
        "afford",
        "investment",
        "limit",
    ],
    "Target Users": [
        "who",
        "people",
        "family",
        "member",
        "kid",
        "child",
        "children",
        "baby",
        "pet",
        "dog",
        "cat",
        "elderly",
        "parent",
        "couple",
        "single",
    ],
    "Style Preference": [
        "style",
        "preference",
        "modern",
        "minimal",
        "nordic",
        "scandinavian",
        "industrial",
        "vintage",
        "retro",
        "luxury",
        "chinese",
        "japanese",
        "wabi-sabi",
        "color",
        "tone",
        "vibe",
        "aesthetic",
        "feel",
    ],
    "Lifestyle Patterns": [
        "lifestyle",
        "habit",
        "hobby",
        "cook",
        "work",
        "study",
        "read",
        "party",
        "guest",
        "entertain",
        "yoga",
        "gym",
        "movie",
        "game",
    ],
    "Personalized Needs": [
        "special",
        "personal",
        "specific",
        "feng shui",
        "smart home",
        "automation",
        "unique",
        "custom",
        "collection",
        "religion",
    ],
    "Storage Requirements": [
        "storage",
        "store",
        "cabinet",
        "shelf",
        "shelves",
        "closet",
        "wardrobe",
        "drawer",
        "organize",
        "clutter",
        "space for",
    ],
    "Inspiration Images": [
        "inspiration",
        "reference",
        "image",
        "photo",
        "picture",
        "example",
        "mood board",
        "pinterest",
        "look like",
    ],
}
